[workspace]
resolver = "3"
members = ["urushi", "urushi-adapter-ratatui", "urushi-cli", "urushi-derive", "urushi-graphics", "urushi-prompt", "urushi-terminal", "urushi-tui", "urushi-tui-app"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
unicode-segmentation = "1.13"
unicode-width = "0.2"
