[workspace]
resolver = "3"
members = ["urushi", "urushi-adapter-ratatui", "urushi-cli", "urushi-derive", "urushi-graphics", "urushi-prompt", "urushi-terminal", "urushi-tui", "urushi-tui-app"]

[workspace.package]
version = "0.1.1"
edition = "2024"
rust-version = "1.90"
license = "MIT"
repository = "https://github.com/choplin/urushi"

[workspace.dependencies]
unicode-segmentation = "1.13"
unicode-width = "0.2"
