allow-branch = ["main"]
shared-version = "workspace"
dependent-version = "upgrade"
consolidate-commits = true

pre-release-commit-message = "build(release): prepare crates for {{version}}"

tag = true
tag-name = "v{{version}}"
tag-message = "urushi {{version}}"

publish = true
verify = true
enable-all-features = true

push = true
push-remote = "origin"
