[package]
name = "urushi-prompt"
description = "Interactive terminal prompts styled with urushi"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
unicode-segmentation.workspace = true
urushi = { path = "../urushi", version = "=0.1.0" }
urushi-terminal = { path = "../urushi-terminal", version = "=0.1.0" }

[target.'cfg(not(unix))'.dependencies]
urushi-terminal = { path = "../urushi-terminal", version = "=0.1.0", features = ["crossterm"] }
