[package]
name = "urushi-tui"
description = "Synchronous full-screen presentation for Urushi"
documentation = "https://docs.rs/urushi-tui"
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["terminal", "tui"]
categories = ["command-line-interface"]

[dependencies]
compact_str = "0.9.1"
urushi = { path = "../urushi", version = "=0.1.1" }
urushi-terminal = { path = "../urushi-terminal", version = "=0.1.1" }
unicode-width.workspace = true

[features]
default = ["crossterm"]
crossterm = ["urushi-terminal/crossterm"]

[[bench]]
name = "cell_buffer"
harness = false

[dev-dependencies]
divan = "0.1.21"
