//! Generates Urushi's built-in theme catalog from an iTerm2-Color-Schemes snapshot.
//!
//! Compile and run this file directly so updating generated data does not add a
//! build-time dependency to the workspace:
//!
//! ```text
//! rustc tools/generate_theme_catalog.rs -o /tmp/generate-theme-catalog
//! /tmp/generate-theme-catalog path/to/iTerm2-Color-Schemes/ghostty \
//!   urushi/src/theme/generated_presets.rs urushi/THEME_CREDITS.md
//! ```

use std::{
    env,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

const SOURCE_REVISION: &str = "fc73ce39746540b6d5ec6b91e304785431401d85";
const EXPECTED_THEME_COUNT: usize = 463;

#[derive(Clone, Copy)]
struct Rgb(u8, u8, u8);

struct SourceTheme {
    name: String,
    background: Rgb,
    foreground: Rgb,
    palette: [Option<Rgb>; 16],
}

fn main() {
    let mut arguments = env::args_os().skip(1);
    let source = PathBuf::from(arguments.next().expect("missing source theme directory"));
    let output = PathBuf::from(arguments.next().expect("missing generated output path"));
    let credits_output = PathBuf::from(arguments.next().expect("missing credits output path"));
    assert!(
        arguments.next().is_none(),
        "expected exactly three arguments"
    );

    let mut paths = fs::read_dir(&source)
        .expect("source theme directory is readable")
        .map(|entry| entry.expect("theme directory entry is readable").path())
        .filter(|path| path.is_file())
        .collect::<Vec<_>>();
    paths.sort_by(|left, right| left.file_name().cmp(&right.file_name()));

    let themes = paths
        .iter()
        .map(|path| parse_theme(path))
        .collect::<Vec<_>>();
    assert_eq!(
        themes.len(),
        EXPECTED_THEME_COUNT,
        "the source snapshot has changed"
    );

    let mut generated = String::new();
    writeln!(
        generated,
        "// @generated by tools/generate_theme_catalog.rs"
    )
    .unwrap();
    writeln!(generated, "// Source: https://github.com/mbadolato/iTerm2-Color-Schemes/tree/{SOURCE_REVISION}/ghostty").unwrap();
    writeln!(generated, "// Do not edit by hand.\n").unwrap();
    writeln!(
        generated,
        "pub(super) static THEME_PRESETS: [ThemePreset; {}] = [",
        themes.len()
    )
    .unwrap();
    for index in 0..themes.len() {
        writeln!(generated, "    ThemePreset({index}),").unwrap();
    }
    writeln!(generated, "];\n").unwrap();
    writeln!(
        generated,
        "pub(super) static THEME_DATA: [ThemeData; {}] = [",
        themes.len()
    )
    .unwrap();
    for theme in &themes {
        let dark = is_dark(theme.background);
        let offset = if dark { 8 } else { 0 };
        writeln!(generated, "    ThemeData {{").unwrap();
        writeln!(generated, "        name: {:?},", theme.name).unwrap();
        writeln!(
            generated,
            "        scheme: ColorScheme::{},",
            if dark { "Dark" } else { "Light" }
        )
        .unwrap();
        writeln!(generated, "        palette: PaletteTheme {{").unwrap();
        write_rgb(&mut generated, "foreground", theme.foreground, 12);
        write_rgb(&mut generated, "background", theme.background, 12);
        for (field, index) in [("red", 1), ("green", 2), ("yellow", 3), ("blue", 4)] {
            write_rgb(
                &mut generated,
                field,
                theme.palette[index + offset].expect("required palette color is present"),
                12,
            );
        }
        writeln!(generated, "        }},").unwrap();
        writeln!(generated, "    }},").unwrap();
    }
    writeln!(generated, "];").unwrap();

    fs::write(output, generated).expect("generated theme catalog is writable");

    let upstream_credits = fs::read_to_string(
        source
            .parent()
            .expect("theme directory has a repository parent")
            .join("CREDITS.md"),
    )
    .expect("upstream credits are readable");
    let upstream_credits = upstream_credits
        .strip_prefix("# Credits\n")
        .unwrap_or(&upstream_credits);
    let credits = format!(
        "# Theme credits\n\n\
         This file preserves the credits from the pinned \
         [iTerm2-Color-Schemes snapshot](https://github.com/mbadolato/iTerm2-Color-Schemes/tree/{SOURCE_REVISION}) \
         used to generate Urushi's built-in theme catalog.\n{upstream_credits}"
    );
    fs::write(credits_output, credits).expect("theme credits are writable");
}

fn parse_theme(path: &Path) -> SourceTheme {
    let name = path
        .file_name()
        .and_then(|name| name.to_str())
        .expect("theme name is UTF-8")
        .to_owned();
    let contents = fs::read_to_string(path).expect("theme file is UTF-8");
    let mut background = None;
    let mut foreground = None;
    let mut palette = [None; 16];

    for line in contents.lines().map(str::trim) {
        if let Some(value) = line.strip_prefix("background =") {
            background = Some(parse_rgb(value));
        } else if let Some(value) = line.strip_prefix("foreground =") {
            foreground = Some(parse_rgb(value));
        } else if let Some(value) = line.strip_prefix("palette =") {
            let (index, color) = value.split_once('=').expect("palette entry has an index");
            let index = index
                .trim()
                .parse::<usize>()
                .expect("palette index is numeric");
            if index < palette.len() {
                palette[index] = Some(parse_rgb(color));
            }
        }
    }

    SourceTheme {
        name,
        background: background.expect("theme has a background"),
        foreground: foreground.expect("theme has a foreground"),
        palette,
    }
}

fn parse_rgb(value: &str) -> Rgb {
    let value = value.trim().strip_prefix('#').unwrap_or(value.trim());
    assert_eq!(value.len(), 6, "RGB colors use six hexadecimal digits");
    Rgb(
        u8::from_str_radix(&value[0..2], 16).expect("red channel is hexadecimal"),
        u8::from_str_radix(&value[2..4], 16).expect("green channel is hexadecimal"),
        u8::from_str_radix(&value[4..6], 16).expect("blue channel is hexadecimal"),
    )
}

fn is_dark(background: Rgb) -> bool {
    let red = f32::from(background.0) / 255.0;
    let green = f32::from(background.1) / 255.0;
    let blue = f32::from(background.2) / 255.0;
    0.2126 * red + 0.7152 * green + 0.0722 * blue < 0.5
}

fn write_rgb(output: &mut String, field: &str, color: Rgb, indentation: usize) {
    writeln!(
        output,
        "{space:indentation$}{field}: Rgb(0x{red:02x}, 0x{green:02x}, 0x{blue:02x}),",
        space = "",
        red = color.0,
        green = color.1,
        blue = color.2,
    )
    .unwrap();
}
